### PR TITLE
Debug mode crashfix + minor tweaks

### PR DESCRIPTION
**Pull request by pryon**
- fixed crash (issue #21) that occured when enabling the debug window
- added a few missing last-function tracers
- added VS2015's IntelliSense database to gitignore

### CODE REVIEW

**Comment by THE-FYP** [comment]
Thanks for contribution, but this PR cannot be accepted because this is not the way how the Debug feature should be fixed. `Read/WriteProcessMemory` was replaced with `memcpy` by two reasons: first - there is no real need to use these functions and second - they are strongly affects on performance. Instead of returing `Read/WriteProcessMemory` back, the Debug function needs to be fixed itself via adding additional checks using `isBadPtr_handlerAny` or similar function.
I can accept only the remaining two changes, if you are ok with that.
And please, next time split the different changes for individual commits.

**Comment by pryon** [comment]
Fair enough.
I wasn't aware of the performance issues that `Read/WriteProcessMemory` would reintroduce.
I'm assuming you want to ditch `memcpy_safe` as well, right?
That way, fixing the Debug feature will be more difficult. The majority of the function has to be rewritten, because it "trusts" the data it receives when using `memcpy_safe`, which was designed to avoid Access Violation exceptions in the first place. Also, because of all the checks and extra code introduced, our problematic function would become even longer and more difficult to read.
Rewriting only `memcpy_safe` (to not use `Read/WriteProcessMemory`) itself would involve changing less code while not changing the `RenderDebug` function at all, but I'm not sure about its performance implications. Still I think it would make more sense to first try to write a fast and reliable `memcpy_safe` before deciding to overhaul the entire `RenderDebug` function itself.
What do you think?

**Comment by pryon** [comment]
Give this one a performance test.

**Comment by THE-FYP** [comment]
>I think it would make more sense to first try to write a fast and reliable memcpy_safe before deciding to overhaul the entire RenderDebug function itself.
>What do you think?
Yes, I agree, that's the point of this function is to be safe. Your last commit seems to be covers all these issues.
Thanks.

**Pull request merged**
